# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tds2Qgis
                                 A QGIS plugin
 DESCRIPTION
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-08
        copyright            : (C) 2022 by Pedro Ceccopieri
        email                : pedroca.mc2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load tds2Qgis class from file tds2Qgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tds2qgis import tds2Qgis
    return tds2Qgis(iface)
